config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  get 'battle/test'
  devise_for :users, :controllers =>{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'registrations/index', to:'users/registrations#index'
    get 'registrations/phone', to:'users/registrations#phone'
    get 'registrations/adress', to:'users/registrations#adress'
    get 'registrations/pay', to:'users/registrations#pay'
    get 'registrations/finish', to:'users/registrations#finish'
    
  end

  root to: "products#index"
  resources :products do
    member do
      get :transaction_buy
      get :crente_buy
      post 'pay', to: 'products#pay'
      get 'done', to: 'products#done'
    end
  end
  resources :users do
    member do
      get :user_edit
    end
    collection do
      get :log_out
    end
  end
  resources :adresses
  resources :credits
  resources :categories

  resources :momo

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get :add
    end
  end
end

app/models/adress.rb
class Adress < ApplicationRecord
  belongs_to :user
  validates :phone_number, numericality: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :products
end

app/models/battle.rb
class Battle < ApplicationRecord
  enum status:{attack: 0,spells:1,defend:2,item:3, abilities:4}
#atttak=攻撃、spells=魔法、defend=防御、item=アイテム、abilities=特技

end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry

end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
  mount_uploader :src, ImageUploader
  
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :text, :status,:delivery_days,:burden,:way,:price, presence: true
  validates :name, length: {maximum: 40}
  validates :text, length: {maximum: 1000}
  has_many :images,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :area
  belongs_to :category
  belongs_to :user
  # mount_uploaders :images, ImageUploader
  enum status:{"新品":0,"未使用に近い":1,"目立った傷や汚れなし":2,"やや傷や汚れあり":3,"傷や汚れあり": 4,"汚れあり": 5}
  enum burden:{"送料込み": 0,"着払い": 1}
  enum delivery_days:{"１~２日で発送": 0,"2~3日で発送": 1,"4~7日で発送": 2}
  enum way:{"未定": 0,"らくらくメルカリ便": 1,"ゆうメール": 2,"レターパック": 3,"普通郵便（定型、定型外": 4,"クロネコヤマト": 5,"ゆうパック": 6,"クリックポスト": 7,"ゆうパケット": 8}


end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_one :adress
  has_many :sns_credentials, dependent: :destroy
  # has_one :adress
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
validates :nickname, presence: true
validates :email, presence: true
validates :password,presence: true,length: { minimum: 7, maximum: 200 }, on: :create
validates :family_name, presence: true
validates :first_name, presence: true

validates :family_name_kana, presence: true
validates :first_name_kana, presence: true
validates :birth_day, presence: true 

def self.without_sns_data(auth)
  user = User.find_by(email: auth.info.email)

    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    return { user: user ,sns: sns}
  end

 def self.with_sns_data(auth, snscredential)
  user = User.find_by(id: snscredential.user_id)
  unless user.present?
    user = User.new(
      nickname: auth.info.name,
      email: auth.info.email,
    )
  end
  return {user: user}
 end

 def self.find_oauth(auth)
  uid = auth.uid
  provider = auth.provider
  snscredential = SnsCredential.find_by(uid: uid, provider: provider)
  if snscredential.present?
    user = with_sns_data(auth, snscredential)[:user]
    sns = snscredential
  else
    user = without_sns_data(auth)[:user]
    sns = without_sns_data(auth)[:sns]
  end
  return { user: user ,sns: sns}
end

validates :family_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
validates :first_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    
    redirect_to action: "show" if card.exists?
  end

  def add
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        if URI(request.referer).path == "/card/new"
          redirect_to action: "show"
        else
          redirect_to registrations_finish_path
        end
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "add"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/momo_controller.rb
class MomoController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/momo_helper.rb
module MomoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card/add.html.haml
.oya-content
  =render '/layouts/header'
  .kodomo-content
    =render '/layouts/sidenav'
    .mago-content 
      %h2.mago-content__top 支払い方法
      .mago-content__midle
        .mago-content__midle__up クレジットカード一覧
        .mago-content__midle__senter
          .mago-content__midle__senter__addbox
            .mago-content__midle__senter__addbox__l
              .mago-content__midle__senter__addbox__m
                %i.far.fa-credit-card
              =link_to new_card_path do
                .mago-content__midle__senter__addbox__s
                  クレジットカードを追加する
        
        .mago-content__midle__bottom 支払い方法について
        

  =link_to new_product_path do
    .sale-logo
      出品
      %i.fa.fa-camera
  
  =render '/layouts/footer'

app/views/card/new.html.haml
.info
  =render '/layouts/header'
  .info__wrapper
    =render '/layouts/sidenav'
    .info__form
      %h3.info__form-heading クレジットカード情報入力
      = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .info__form-sentence
          %label カード番号 
          %span 必須
        = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        %ul.credit__list
          %li
            =link_to ""  do
              =image_tag "/credit/card_logo.png",class:"credit__list-image"
          %li
            =link_to ""  do
              =image_tag "/credit/master300px.gif",class:"credit__list-image"
          %li
            =link_to ""  do
              =image_tag "/credit/saison300px.gif",class:"credit__list-image"
          %li
            =link_to ""  do
              =image_tag "/credit/jcb300px.gif",class:"credit__list-image"
          %li
            =link_to ""  do
              =image_tag "/credit/diners300px.gif",class:"credit__list-image"

        %br
        .info__form-sentence
          %label 有効期限
          %span 必須
        %select#exp_month{name: "exp_month", type: "text"}
          %option{value: ""} --
          %option{value: "1"}01
          %option{value: "2"}02
          %option{value: "3"}03
          %option{value: "4"}04
          %option{value: "5"}05
          %option{value: "6"}06
          %option{value: "7"}07
          %option{value: "8"}08
          %option{value: "9"}09
          %option{value: "10"}10
          %option{value: "11"}11
          %option{value: "12"}12
        %span 月/
        %select#exp_year{name: "exp_year", type: "text"}
          %option{value: ""} --
          %option{value: "2019"}19
          %option{value: "2020"}20
          %option{value: "2021"}21
          %option{value: "2022"}22
          %option{value: "2023"}23
          %option{value: "2024"}24
          %option{value: "2025"}25
          %option{value: "2026"}26
          %option{value: "2027"}27
          %option{value: "2028"}28
          %option{value: "2029"}29
        %span 年
        %br
        %label セキュリティコード
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
        = submit_tag "追加する", id: "token_submit"
        
  =render '/momo/footter'

app/views/card/show.html.haml
.oya-content
  =render '/layouts/header'
  .kodomo-content
    =render '/layouts/sidenav'
    .mago-content 
      %h2.mago-content__top 支払い方法
      .mago-content__midle
        .mago-content__midle__up クレジットカード一覧
        .mago-content__midle__senter
          .mago-content__midle__senter__ue 
            %br
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button 削除する
        .mago-content__midle__bottom 支払い方法について

    

=link_to new_product_path do
  .sale-logo
    出品
    %i.fa.fa-camera

=render '/layouts/footer'