config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  get 'battle/test'
  devise_for :users, :controllers =>{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'registrations/index', to:'users/registrations#index'
    get 'registrations/phone', to:'users/registrations#phone'
    get 'registrations/adress', to:'users/registrations#adress'
    get 'registrations/pay', to:'users/registrations#pay'
    get 'registrations/finish', to:'users/registrations#finish'
    
  end

  root to: "products#index"
  resources :products do
    member do
      get :transaction_buy
      get :crente_buy
      post 'pay', to: 'products#pay'
      get 'done', to: 'products#done'
    end
  end
  resources :users do
    member do
      get :user_edit
    end
    collection do
      get :log_out
    end
  end
  resources :adresses
  resources :credits
  resources :categories

  resources :momo

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get :add
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :text, :status,:delivery_days,:burden,:way,:price, presence: true
  validates :name, length: {maximum: 40}
  validates :text, length: {maximum: 1000}
  has_many :images,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :area
  belongs_to :category
  belongs_to :user
  # mount_uploaders :images, ImageUploader
  enum status:{"新品":0,"未使用に近い":1,"目立った傷や汚れなし":2,"やや傷や汚れあり":3,"傷や汚れあり": 4,"汚れあり": 5}
  enum burden:{"送料込み": 0,"着払い": 1}
  enum delivery_days:{"１~２日で発送": 0,"2~3日で発送": 1,"4~7日で発送": 2}
  enum way:{"未定": 0,"らくらくメルカリ便": 1,"ゆうメール": 2,"レターパック": 3,"普通郵便（定型、定型外": 4,"クロネコヤマト": 5,"ゆうパック": 6,"クリックポスト": 7,"ゆうパケット": 8}


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index,:new, :create]
  before_action :current_user_user_id? ,only: [:pay,:transaction_buy,:crente_buy]
  before_action :not_current_user_user_id? ,only: [:edit, :update, :destroy]
  
  
  require 'payjp'
  def index
    @categories = Category.roots.all
  end

  def new
    @product = Product.new
    @product.images.build
    @areas = Area.all
    @categories_roots = Category.roots
  end
  
  def create
    image = params.require(:product).permit(images_attributes:  [:id])
    if image.blank?
      redirect_to new_product_path
      else
      @product=Product.new(product_params)
      if @product.save
        redirect_to root_path
      else
        render action: :new
      end
    end
  end

  def edit
    @areas = Area.all
    @categories_roots = Category.roots
    @product.images.build
  end

  def update
    @images=@product.images
    # binding.pry

    if @product.images
      @product.update(product_edit_params)
      redirect_to root_path
    else
      redirect_to edit_product_path(@product)
    end
  end

  def destroy
    @product.destroy
    redirect_to user_path(current_user)
    
  end
  
  def transaction_buy
    if @product.buy_user.present?
      redirect_to product_path(@product)
    end
    @adress = @product.user.adress
    @product = Product.find(params[:id])
    card = Card.find_by(params[:id])
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay
    @product = Product.find(params[:id])
    card = Card.find_by(params[:id])
    Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    Payjp::Charge.create(
    amount: @product.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: card.customer_id, #顧客ID
    currency: 'jpy', #日本円
  )
  redirect_to action: 'done' #完了画面に移動 
  end

  def crente_buy
    @product.update(buy_user:current_user.id,sale: "購入")
    redirect_to root_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :text, :category_id, :size, :brand, :status, :burden, :way, :area_id, :delivery_days,:price , images_attributes: [:id,:src]).merge(user_id:current_user.id)
  end

  def product_edit_params
    params.require(:product).permit(:name, :text, :category_id, :size, :brand, :status, :burden, :way, :area_id, :delivery_days,:price , images_attributes: [:_destroy,:id,:src]).merge(user_id:current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def current_user_user_id?
    if current_user.id == @product.user_id
      redirect_to root_path
    end
  end

  def not_current_user_user_id?
    if current_user.id != @product.user_id
      redirect_to root_path
    end
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_card.html.haml
.card-wrapper
  =link_to product_path(product) do
    .card
      .card__top
        - if product.buy_user == nil
          =image_tag product.images[0].src.url,class:"card__top-image"
        - else
          =image_tag "/shopping.png",class:"card__top-image"

        .card__top-price 
          ="¥#{product.price}"
      .card__bottom
        %p.card__bottom-text
          =product.text 

app/views/products/_category.html.haml
.category-new
  %h3.women-new-item #{category.name}新着アイテム
  =link_to "もっと見る >",category_path(category),class:'category-new-link'
.category__products
  -category.products.each do |product|
    = render partial: "card" ,locals:{ product: product}

app/views/products/_show_card.html.haml
//show.scss
.items-boxs
  .items-box
    =link_to "" do
      .items-box-photo
        =image_tag '/otya2.png', class: ''
      .items-box-body
        .items-box-name
          お茶お茶お茶
        .items-box-num
          .items-box-price
            ¥4,800

app/views/products/done.html.haml
%header.header
  = link_to crente_buy_product_path do
    = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3296506464', class: 'rootlink'
%h2 購入が完了しました！

=link_to crente_buy_product_path do
  .return__top
    TOPへ戻る
%footter.footter
  .single-footer
    %ul.login-footer-list
      %li
        = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li
        = link_to "メルカリ規約", "https://www.mercari.com/jp/privacy/"
      %li
        = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/privacy/" 
    = link_to crente_buy_product_path do
      = image_tag  'https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3296506464', class: 'root-link-fooder'
    %p.login-footer-list-text
      ©︎2019 Mercari

app/views/products/edit.html.haml
.sell-wrappe
  =render "/momo/header"
  .sell
    = form_with model:@product,local: true do |f|
      %h3.sell__title 商品の情報を入力
      .sell__image
        = f.label :image, "出品画像"
        %span.required
        %p.max 最大10枚までアップロードできます
        .sell-image
          .sell__image-output
            -@product.images.each_with_index do |image, i|
              -if image.persisted?
                .image-wrapper
                  = image_tag image.src.url, class:'output'
                  .image_remove{data:{index: i}}
                    削除
          .sell__image-select
            = f.fields_for :images do |image|
              =image.label :src ,class:'label',data:{index:@product.images.count} do
                =image.file_field :src,class:'file_form'
              - if image.object.persisted?
                = image.check_box :_destroy,class:'hidden'
                = image.label :_destroy, "",class:"image_destroy"
            .sell__image-select-text またはクリックしてファイルをアップロード


      .sell__about
        .sell__about__name
          = f.label :name, "商品名"
          %span.required
          = f.text_field :name,  placeholder: "商品名（必須40文字まで）",class: "form"
        .sell__about__description
          = f.label :text, "商品の説明"
          %span.required
          = f.text_area :text, class: "sell__about-description__form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
          
      .sell__about.clearfix
        .sell__about__left 商品の詳細 
        .sell__about__right
          .sell__about__right__wrap
            = f.label :category_id, "カテゴリー"
            %span.required
            .sell__about__right__wrap-box
              = f.select :category_id, @categories_roots.map{|category| [category.name, category.id]}, prompt: "---", class: "select"
              %i.fas.fa-chevron-down
            -# .sell__about__right__wrap-box-none
            -#   = f.select :category, [["赤"],["黄ばみ"]], prompt: "---", class: "select"
            -#   %i.fas.fa-chevron-down
            -# .sell__about__right__wrap-box-none
            -#   = f.select :category, [["赤"],["黄"]], prompt: "---", class: "select"
            -#   %i.fas.fa-chevron-down
          .sell__about__right__wrap
            = f.label :size, "サイズ"
            %span.required
            .sell__about__right__wrap-box
              = f.select :size, [["赤",0],["黄",1]], prompt: "---", class: "select"
              %i.fas.fa-chevron-down
              
          .sell__about__right__wrap-box
            = f.label :brand, "ブランド"
            %span.required-gray
            .sell__about__right__wrap-box
              = f.text_field :brand, placeholder: "例）シャネル", class: "form"
          .sell__about__right__wrap
            = f.label :status, "商品の状態"
            
            %span.required
            .sell__about__right__wrap-box
              = f.select :status,Product.statuses.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

      .sell__about.clearfix
        .sell__about__left 配送について
        .sell__about__right

          .sell__about__right__wrap
            = f.label :burden, "配送料の負担"
            %span.required
            .sell__about__right__wrap-box
              = f.select :burden, Product.burdens.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

          .sell__about__right__wrap-box
            = f.label :way, "配送の方法"
            %span.required
            .sell__about__right__wrap-box
              = f.select :way, Product.ways.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

          .sell__about__right__wrap
            = f.label :area_id, "配送元の地域"
            %span.required
            .sell__about__right__wrap-box
              = f.select :area_id, @areas.map{|area| [area.name,area.id]}, prompt: "---", class: "select"
              %i.fas.fa-chevron-down
          .sell__about__right__wrap
            = f.label :delivery_days, "配送までの日数"
            %span.required
            .sell__about__right__wrap-box
              = f.select :delivery_days, Product.delivery_days.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

      .sell__about.clearfix
        .sell__about__left 販売価格(300〜9,999,999)
        .sell__about__right
          .sell__about__right__wrap
            .sell__about__right__wrap__price
              .sell__about__right__wrap__price-label
                = f.label :price, "価格"
                %span.required
              .sell__about__right__wrap__price-input
                ¥
                .sell__about__right__wrap__price-input-form
                  = f.number_field :price, placeholder: "例）300", class: "form"

            .sell__about__right__wrap__fee
              .sell__about__right__wrap__fee-left
                販売手数料 (10%)
              .sell__about__right__wrap__fee-right
                −
            .sell__about__right__wrap__profit
              .sell__about__right__wrap__profit-left
                販売利益
              .sell__about__right__wrap__profit-right
                −
      .sell__about.clearfix
        .sell__about__bottom
          .sell__about__bottom-text
            %p
              = link_to '#' do
                禁止されている出品
              、
              = link_to '#' do
                行為
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to '#' do
                偽ブランド
              の販売は犯罪であり処罰される可能性があります。
            %p 
              また、出品をもちまして
              = link_to '#' do
                加盟店規約
              に同意したことになります。
          = f.submit "編集する", class: 'sell__about__bottom-btn submit'
          %button{type: "button", class: 'sell__about__bottom-btn back'} もどる
=render '/momo/footter'

app/views/products/index.html.haml
=render '/layouts/header'

.slide
  =image_tag "/cb396095b5f07e7117201fe2c2980ee1.png" ,class:"slide-image"
  =image_tag "" ,class:""

.category
  .category__heading
    %h3.popularity
      人気のカテゴリー
    %ul.category__heading-list
      -@categories.each do |category|
        %li
          =link_to category.name ,category_path(category)
  .container
    = render partial: "category" ,collection: @categories

=render '/layouts/sale-logo'
=render '/layouts/footer'

app/views/products/new.html.haml
.sell-wrappe
  =render "/momo/header"
  .sell
    = form_with model:@product,local: true do |f|
      %h3.sell__title 商品の情報を入力
      .sell__image
        = f.label :image, "出品画像"
        %span.required
        %p.max 最大10枚までアップロードできます
        .sell-image
          .sell__image-output
          .sell__image-select
            = f.fields_for :images do |image|
              =image.label :src ,class:'label',data:{index:"0"} do
                =image.file_field :src,class:'file_form'
            .sell__image-select-text またはクリックしてファイルをアップロード


      .sell__about
        .sell__about__name
          = f.label :name, "商品名"
          %span.required
          = f.text_field :name,  placeholder: "商品名（必須40文字まで）",class: "form"
        .sell__about__description
          = f.label :text, "商品の説明"
          %span.required
          = f.text_area :text, class: "sell__about-description__form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
          
      .sell__about.clearfix
        .sell__about__left 商品の詳細 
        .sell__about__right
          .sell__about__right__wrap
            = f.label :category_id, "カテゴリー"
            %span.required
            .sell__about__right__wrap-box
              = f.select :category_id, @categories_roots.map{|category| [category.name, category.id]}, prompt: "---", class: "select"
              %i.fas.fa-chevron-down
            -# .sell__about__right__wrap-box-none
            -#   = f.select :category, [["赤"],["黄ばみ"]], prompt: "---", class: "select"
            -#   %i.fas.fa-chevron-down
            -# .sell__about__right__wrap-box-none
            -#   = f.select :category, [["赤"],["黄"]], prompt: "---", class: "select"
            -#   %i.fas.fa-chevron-down
          .sell__about__right__wrap
            = f.label :size, "サイズ"
            %span.required
            .sell__about__right__wrap-box
              = f.select :size, [["赤",0],["黄",1]], prompt: "---", class: "select"
              %i.fas.fa-chevron-down
              
          .sell__about__right__wrap-box
            = f.label :brand, "ブランド"
            %span.required-gray
            .sell__about__right__wrap-box
              = f.text_field :brand, placeholder: "例）シャネル", class: "form"
          .sell__about__right__wrap
            = f.label :status, "商品の状態"
            
            %span.required
            .sell__about__right__wrap-box
              = f.select :status,Product.statuses.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

      .sell__about.clearfix
        .sell__about__left 配送について
        .sell__about__right

          .sell__about__right__wrap
            = f.label :burden, "配送料の負担"
            %span.required
            .sell__about__right__wrap-box
              = f.select :burden, Product.burdens.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

          .sell__about__right__wrap-box
            = f.label :way, "配送の方法"
            %span.required
            .sell__about__right__wrap-box
              = f.select :way, Product.ways.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

          .sell__about__right__wrap
            = f.label :area_id, "配送元の地域"
            %span.required
            .sell__about__right__wrap-box
              = f.select :area_id, @areas.map{|area| [area.name,area.id]}, prompt: "---", class: "select"
              %i.fas.fa-chevron-down
          .sell__about__right__wrap
            = f.label :delivery_days, "配送までの日数"
            %span.required
            .sell__about__right__wrap-box
              = f.select :delivery_days, Product.delivery_days.keys {}, {class: "select"}
              %i.fas.fa-chevron-down

      .sell__about.clearfix
        .sell__about__left 販売価格(300〜9,999,999)
        .sell__about__right
          .sell__about__right__wrap
            .sell__about__right__wrap__price
              .sell__about__right__wrap__price-label
                = f.label :price, "価格"
                %span.required
              .sell__about__right__wrap__price-input
                ¥
                .sell__about__right__wrap__price-input-form
                  = f.number_field :price, placeholder: "例）300", class: "form"

            .sell__about__right__wrap__fee
              .sell__about__right__wrap__fee-left
                販売手数料 (10%)
              .sell__about__right__wrap__fee-right
                −
            .sell__about__right__wrap__profit
              .sell__about__right__wrap__profit-left
                販売利益
              .sell__about__right__wrap__profit-right
                −
      .sell__about
        .sell__about__bottom-text
          %p
            = link_to '#' do
              禁止されている出品
            、
            = link_to '#' do
              行為
            を必ずご確認ください。
          %p
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to '#' do
              偽ブランド
            の販売は犯罪であり処罰される可能性があります。
          %p 
            また、出品をもちまして
            = link_to '#' do
              加盟店規約
            に同意したことになります。
        = f.submit "出品する", class: 'product_submit'
        =link_to root_path do
          %button{type: "button", class: 'sell__about__bottom-btn back'} もどる
=render '/momo/footter'

app/views/products/show.html.haml
=render '/layouts/header'


.default-container




  .item-box-container
    %h1.item-name
      = @product.name
    .item-main-content
      .item-photo
        .owl-carousel
          .owl-stage-outer
            .owl-stage
              -@product.images.each do |image|
                - if @product.buy_user == nil
                  =image_tag image.src.url, class: 'owl-item'
                - else
                  =image_tag "/shopping.png", class: 'owl-item'


            .owl-nav
            .owl-dots
              -@product.images.each do |image|
                =image_tag image.src.url, class: 'owl-dot'


      %table.item-detail-table
        %tr.item-detail-table-tr
          %th.item-detail-table-th  出品者
          %td.item-detail-table-td
            =link_to ""  do
              =@product.user.nickname
            
        %tr.item-detail-table-tr
          %th.item-detail-table-th カテゴリ
          %td.item-detail-table-td
            %ul.item-detail-table_category
              %li
                =link_to ""  do
                  メンズ
              %li
                =link_to ""  do
                  %i.fas.fa-chevron-right 靴
              %li
                =link_to ""  do
                  %i.fas.fa-chevron-right スニーカー
        %tr.item-detail-table-tr
          %th.item-detail-table-th ブランド
          %td.item-detail-table-td
            =link_to ""  do
              ナイキ
        %tr.item-detail-table-tr
          %th.item-detail-table-th 商品状態

          %td.item-detail-table-td 
            = @product.status



          %td.item-detail-table-td 
        %tr.item-detail-table-tr
          %th.item-detail-table-th  配送料の負担
          %td.item-detail-table-td
            = @product.burden
        %tr.item-detail-table-tr
          %th.item-detail-table-th  配達方法
          %td.item-detail-table-td
            = @product.way
        %tr.item-detail-table-tr
          %th.item-detail-table-th  配送元地域
          %td.item-detail-table-td
            =link_to ""  do
              = @product.area.name
        %tr.item-detail-table-tr
          %th.item-detail-table-th  発送日の目安
          %td.item-detail-table-td
            = @product.delivery_days


    .item-price-box.text-center
      %ul.item-price-boxs
        %li.item-price-box-price
          = "¥#{@product.price}"
        %li.item-price-box-tax (税込)
        %li.item-price-box-shipping-fee 送料込み

    - if user_signed_in? && @product.user.id == current_user.id
      =link_to edit_product_path(@product) do
        .edit_btn
          編集する     
  
      .delete_btn
        削除する
      .item-description
        %p.item-description-text
          = @product.text

    - else 
      - if @product.buy_user == nil
        =link_to transaction_buy_product_path do
          .purchase
            購入画面に進む
      - else 
        .item-buy-btn
          売り切れ
    
    
  .item-detail-message
    .message-content
      ここにはメッセージ機能？？？？？
  
  %ul.nav-item-link-prev-next.clearfix
    %li.nav-item-link-prev
      =link_to "" do
        %i.fas.fa-chevron-left
        おーいお茶
    %li.nav-item-link-next
      =link_to "" do
        綾鷹
        %i.fas.fa-chevron-right

  .item-social-media-box
    .text-center
      %ul.text-center-icon
        =link_to "" do
          %li.icon-facebook
            %i.fab.fa-facebook
        =link_to "" do
          %li.icon-twitter
            %i.fab.fa-twitter

        =link_to "" do
          %li.icon-pint
            %i.fab.fa-pinterest



  .items-in-user-profile
    .items-box-container
      =link_to "" do
        .items-box-head
          ●●さんのその他出品
        .items-box-content
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
    .items-box-container
      =link_to "" do
        .items-box-head
          ●ほかの商品
        .items-box-content
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          =render 'show_card'
          











=render '/layouts/footer'


.modal
  .modal_box
    %p.modal_confirmation 確認
    %br/
    %p.modal_reconfirmation 削除すると二度と復活できません。
    %p.modal_reconfirmation 削除する代わりに停止することもできます。
    %br/
    %p.modal_reconfirmation_box 本当に削除しますか？
    %br/
    .modal_box2
      .cancel_box キャンセル
      =link_to product_path(@product),method:"delete" do
        .delete_box 削除
      

app/views/products/transaction_buy.html.haml
.single-container
  = render '/momo/header'

  .single__main
    .l-single-container
      .l-single-head
        購入内容の確認
      .buy-content
        .buy-content-inner_buy
          .buy-item-image
            =image_tag @product.images[0].src.url,class:"buy__image__Photo"
            .buy-item-name
              = @product.name

          .buy-price-boxs
            .buy-price
              %ul.buy-price-box
                %li.buy-price-ja
                  ¥#{@product.price}
                %li.item-shipping-fee
                  送料込み
              .buy-accordion
                ポイントはありません
              %ul.buy-price-table
                %il.buy-price-table-row
                  .buy-price-table-cell-left
                    支払い金額
                  .buy-price-table-cell-right
                    ¥#{@product.price}
              .purchase__button
                .purchase__button__buy
                  = form_tag(action: :pay, method: :post) do
                    %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "購入する" ,"data-key" => "pk_test_942828262fd3fbb4704e8bd7"}
                    -# =link_to crente_buy_product_path do


      .buy-content-2
        .buy-content-inner_buy
          配送先
          .buy-user-info-text
            %p
            = @adress.zipcode
            %br/
            = @adress.prefectures
            = @adress.city
            = @adress.building
            %br/
            = @product.name
            .buy-user-info-fix
              =link_to "", class: "buy-user-info-fix-l" do
                変更する
                %i.fas.fa-chevron-right
      .buy-content-3
        .buy-content-inner_buy
          %h3 支払い方法
          - if @default_card_information.blank?
            %br /
          - else
            
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %br
          .buy-user-info-fix
            =link_to "", class: "buy-user-info-fix-l" do
              変更する
              %i.fas.fa-chevron-right




  = render '/momo/footter'