config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  get 'battle/test'
  devise_for :users, :controllers =>{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'registrations/index', to:'users/registrations#index'
    get 'registrations/phone', to:'users/registrations#phone'
    get 'registrations/adress', to:'users/registrations#adress'
    get 'registrations/pay', to:'users/registrations#pay'
    get 'registrations/finish', to:'users/registrations#finish'
    
  end

  root to: "products#index"
  resources :products do
    member do
      get :transaction_buy
      get :crente_buy
      post 'pay', to: 'products#pay'
      get 'done', to: 'products#done'
    end
  end
  resources :users do
    member do
      get :user_edit
    end
    collection do
      get :log_out
    end
  end
  resources :adresses
  resources :credits
  resources :categories

  resources :momo

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
      get :add
    end
  end
end

app/models/adress.rb
class Adress < ApplicationRecord
  belongs_to :user
  validates :phone_number, numericality: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :products
end

app/models/battle.rb
class Battle < ApplicationRecord
  enum status:{attack: 0,spells:1,defend:2,item:3, abilities:4}
#atttak=攻撃、spells=魔法、defend=防御、item=アイテム、abilities=特技

end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry

end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
  mount_uploader :src, ImageUploader
  
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :text, :status,:delivery_days,:burden,:way,:price, presence: true
  validates :name, length: {maximum: 40}
  validates :text, length: {maximum: 1000}
  has_many :images,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :area
  belongs_to :category
  belongs_to :user
  # mount_uploaders :images, ImageUploader
  enum status:{"新品":0,"未使用に近い":1,"目立った傷や汚れなし":2,"やや傷や汚れあり":3,"傷や汚れあり": 4,"汚れあり": 5}
  enum burden:{"送料込み": 0,"着払い": 1}
  enum delivery_days:{"１~２日で発送": 0,"2~3日で発送": 1,"4~7日で発送": 2}
  enum way:{"未定": 0,"らくらくメルカリ便": 1,"ゆうメール": 2,"レターパック": 3,"普通郵便（定型、定型外": 4,"クロネコヤマト": 5,"ゆうパック": 6,"クリックポスト": 7,"ゆうパケット": 8}


end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_one :adress
  has_many :sns_credentials, dependent: :destroy
  # has_one :adress
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
validates :nickname, presence: true
validates :email, presence: true
validates :password,presence: true,length: { minimum: 7, maximum: 200 }, on: :create
validates :family_name, presence: true
validates :first_name, presence: true

validates :family_name_kana, presence: true
validates :first_name_kana, presence: true
validates :birth_day, presence: true 

def self.without_sns_data(auth)
  user = User.find_by(email: auth.info.email)

    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    return { user: user ,sns: sns}
  end

 def self.with_sns_data(auth, snscredential)
  user = User.find_by(id: snscredential.user_id)
  unless user.present?
    user = User.new(
      nickname: auth.info.name,
      email: auth.info.email,
    )
  end
  return {user: user}
 end

 def self.find_oauth(auth)
  uid = auth.uid
  provider = auth.provider
  snscredential = SnsCredential.find_by(uid: uid, provider: provider)
  if snscredential.present?
    user = with_sns_data(auth, snscredential)[:user]
    sns = snscredential
  else
    user = without_sns_data(auth)[:user]
    sns = without_sns_data(auth)[:sns]
  end
  return { user: user ,sns: sns}
end

validates :family_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
validates :first_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/momo_helper.rb
module MomoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_breadcrumbs.html.haml
- case params.values_at :controller, :action

- when ['users', 'show']
  - breadcrumb :mypage

- when ['users', 'user_edit']
  - breadcrumb :infomation

- when ['users', 'edit']
  - breadcrumb :profile

- when ['card', 'show']
  - breadcrumb :pay

- when ['card', 'new']
  - breadcrumb :pay

- when ['users', 'log_out']
  - breadcrumb :logout

= breadcrumbs separator: " &rsaquo; "

app/views/layouts/_footer.html.haml
//products.scss
%footer
  =image_tag "/027e61bb6e6e1b9e3c94e408e71dd6e2.png",class:"footer-image"
  .text-area
    %ul.footer__text-area-lists
      %h5.class:footer__text-area_heading メルカリについて
      %li.class:footer__text-area_list 会社概要（運営会社)
      %li.class:footer__text-area_list 採用情報
      %li.class:footer__text-area_list プレリリースコード
      %li.class:footer__text-area_list 公式ブログ
      %li.class:footer__text-area_list メルカリロゴ利用ガイドライン
      %i.fab.fa-twitter
      %i.fab.fa-facebook.footer
    
    %ul.footer__text-area-lists
      %h5.class:footer__text-area_heading ヘルプ＆ガイド
      %li.class:footer__text-area_list らくらくメルカリ便
      %li.class:footer__text-area_list ゆうゆうメルカリ便
      %li.class:footer__text-area_list 大型メルカリ便
      %li.class:footer__text-area_list 車体取引ガイド
      %li.class:footer__text-area_list メルカリあんしん・あんぜん宣言！
      %li.class:footer__text-area_list 偽ブランド品撲滅への取り組み
      %li.class:footer__text-area_list メルカリボックス

    %ul.footer__text-area-lists
      %h5.class:footer__text-area_heading プライバシーポリシー
      %li.class:footer__text-area_list メルカリ利用規約
      %li.class:footer__text-area_list あんしんスマホサポートサービス制度に関する利用特約
      %li.class:footer__text-area_list コンプライアンスポリシー
      %li.class:footer__text-area_list 個人データのあんぜん管理に係る基本方針
      %li.class:footer__text-area_list 特定商取引法に関する表記
      %li.class:footer__text-area_list 資金決済法に基づく表示
      %li.class:footer__text-area_list 法令遵守と犯罪抑止のために

    %ul.footer__text-area-lists
      %h5.class:footer__text-area_heading 国
      %li.class:footer__text-area_list 日本
      %li.class:footer__text-area_list United States



  .footer__icon
    %p.mercari2019 ©︎2019 mercari
    =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-white-1a0696cf557ee1ed6f3c3444661d21ad.svg",class:"footer_icon_image"

app/views/layouts/_header.html.haml
//products.scss
.container__top
  .login-out-main-mai
    .header__top
      =link_to root_path do
        =image_tag "/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg" ,class:"header__top-logo"
      .header__item__search
        =form_with url:"/" do |f|
          .header__item__search__text
            =f.text_field :"",class:"header__top-search",placeholder:"何かお探しですか？"
            %ladel.header__top-button__label
              = button_tag type: 'submit', class: "header__top-button" do
                %i.fa.fa-search
    .header__bottom
      %ul.header__bottom__left
        %li.header__bottom__left-list
          =link_to ""  do
            %i.fa.fa-list-ul
            カテゴリーから探す
        %li.header__bottom__left-list
          =link_to ""  do
            %i.fa.fa-list-ul
            ブランドから探す
      %ul.header__bottom__right
        - if user_signed_in?
          %li.header__bottom__right-list
            =link_to ""  do
              %i.fa.fa-heart
              いいね！一覧
          %li.header__bottom__right-list
            =link_to ""  do
              %i.fa.fa-bell
              お知らせ
          %li.header__bottom__right-list
            =link_to ""  do
              %i.fa.fa-check
              やることリスト
          %li.header__bottom__right-list
            =link_to user_path(current_user)  do
              .my-page__wrapper
                =image_tag "/member_photo_noimage_thumb.png",class:'my-page__wrapper-logo'
                %p.my-page__wrapper-text マイページ
        - else
          %li.header__bottom__right-list
            =link_to registrations_index_path do
              %p.header__bottom__right-list-signup 新規会員登録
          %li.header__bottom__right-list
            =link_to new_user_session_path do
              %p.header__bottom__right-list-login ログイン

=render 'layouts/breadcrumbs'

app/views/layouts/_sale-logo.html.haml
=link_to new_product_path do
  .sale-logo
    出品
    %i.fa.fa-camera

app/views/layouts/_sidenav.html.haml
.side-nav
  %nav.nav-mypage
    %ul.nav-mypage__list
      = link_to user_path(current_user), class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item
          マイページ
          %span.nav-mypage__list-item-number
            3
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          お知らせ
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          やることリスト
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          いいね！一覧
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          出品する
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          出品した商品 - 出品中
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          出品した商品 - 取引中
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          出品した商品 - 売却済み
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          購入した商品 - 取引中
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          購入した商品 - 過去の取引
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          ニュース一覧
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          評価一覧
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          ガイド
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          お問い合わせ
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right


    %h3.nav-mypage__head メルペイ
    %ul.nav-mypage__list
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active   
          売上・振込申請
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active    
          ポイント
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
          

    %h3.nav-mypage__head 設定
    %ul.nav-mypage__list
      = link_to edit_user_path(current_user), class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          プロフィール
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          発送元・お届け先住所変更
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to delete_card_index_path, class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          支払い方法
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          メール/パスワード
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to user_edit_user_path(current_user), class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          本人情報
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to "", class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          電話番号の確認
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right
      = link_to log_out_users_path, class: "nav-mypage__list-link" do
        %li.nav-mypage__list-item.active
          ログアウト
          %span.nav-mypage__list-item-number
          %i.fas.fa-angle-right

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample59b
    %script{:src => "https://js.pay.jp/", :type => "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield